import enum


class SADeviceType(enum.IntEnum):
    """TAISEIA Spec. Constant Table_10"""
    # REGISTER = 0x00
    AIR_CONDITIONER = 0x01
    REFRIGERATOR = 0x02
    WATCHING_MACHINE = 0x03
    DEHUMIDIFIER = 0x04
    TELEVISION = 0x05
    DRYING_MACHINE = 0x06
    HEAD_PUMP_WATER_HEATER = 0x07
    AIR_CLEANER = 0x08
    ELECTRONIC_POT = 0x09
    OPEN_DRINK_MACHINE = 0x0A
    INDUCTION_COOKER = 0x0B
    DISH_WASHER = 0x0C
    MICROWAVE_OVEN = 0x0D
    FULL_HEAT_SWITCH = 0x0E
    FAN = 0x0F
    GAS_WATER_HEATER = 0x10
    LAMP = 0x11
    FAN_SAMPO = 0x13
    SMART_METER_GATEWAY = 0xE0
    GENERAL_DEVICE = 0xF0


class SARegisterServiceID(enum.IntEnum):
    """TAISEIA Spec. Constant Table_14"""
    READ_ALL = 0X00
    READ_DEVICE_CLASS_ID = 0X01
    READ_DEVICE_PROTOCOL_VER = 0X02
    RESERVED = 0X03
    READ_DEVICE_TYPE_ID = 0X04
    READ_DEVICE_BRAND = 0X05
    READ_DEVICE_MODEL = 0X06
    READ_DEVICE_SERVICES = 0X07
    READ_DEVICE_SERVICES_STATUS = 0X08


class SAServiceIOMode(enum.IntEnum):
    READ = 0x00
    READ_WRITE = 0x01


class SAClassID(enum.IntEnum):
    HOME_DEVICE = 0x00
    POWER_DEVICE = 0x01
    ENERGY_STORAGE_DEVICE = 0x02
    SENSOR_DEVICE = 0x03


class SAPacketDataLenType(enum.IntEnum):
    FIXED_LEN = 0
    DYNAMIC_LEN = 1
