import enum


class SATypeID(enum.IntEnum):
    # REGISTER = 0x00
    AIR_CONDITIONER = 0x01
    REFRIGERATOR = 0x02
    WATCHING_MACHINE = 0x03
    DEHUMIDIFIER = 0x04
    TELEVISION = 0x05
    DRYING_MACHINE = 0x06
    HEAD_PUMP_WATER_HEATER = 0x07
    AIR_CLEANER = 0x08
    ELECTRONIC_POT = 0x09
    OPEN_DRINK_MACHINE = 0x0A
    INDUCTION_COOKER = 0x0B
    DISH_WASHER = 0x0C
    MICROWAVE_OVEN = 0x0D
    FULL_HEAT_SWITCH = 0x0E
    FAN = 0x0F
    GAS_WATER_HEATER = 0x10
    LAMP = 0x11
    FAN_SAMPO = 0x13
    SMART_METER_GATEWAY = 0xE0
    GENERAL_DEVICE = 0xF0
    ERROR = 0xFF
